// <auto-generated>
// Written by tools/art/measure_frames.py from the frames' pixels: where each art set's Plate Frame
// and Portrait Frame is cut so it fits any box (ArtFrameSlices: columns, then rows, in runtime
// pixels). Edit the script and run it again rather than editing this file.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace AetherFrame.Domain.Components;

internal static class ArtFrameData
{
    /// <summary>Each art set's Plate Frame and Portrait Frame cuts, by the set's folder (Celestial Sakura's included).</summary>
    internal static readonly IReadOnlyDictionary<string, (ArtFrameSlices PlateFrame, ArtFrameSlices PortraitFrame)> ByFolder =
        new Dictionary<string, (ArtFrameSlices PlateFrame, ArtFrameSlices PortraitFrame)>(StringComparer.Ordinal)
        {
            ["AlchemistsWorkshop"] = (
                new ArtFrameSlices(new ArtSlices(20, 291, 836, 836, 1382, 1654), new ArtSlices(14, 307, 470, 470, 627, 921)),
                new ArtFrameSlices(new ArtSlices(9, 265, 496, 496, 727, 984), new ArtSlices(9, 323, 793, 793, 1257, 1576))),
            ["AllaganTech"] = (
                new ArtFrameSlices(new ArtSlices(16, 239, 836, 836, 1433, 1657), new ArtSlices(16, 217, 470, 470, 707, 910)),
                new ArtFrameSlices(new ArtSlices(32, 270, 496, 496, 721, 960), new ArtSlices(44, 265, 793, 793, 1314, 1539))),
            ["AncientAmaurot"] = (
                new ArtFrameSlices(new ArtSlices(20, 230, 836, 836, 1442, 1653), new ArtSlices(15, 217, 470, 470, 724, 925)),
                new ArtFrameSlices(new ArtSlices(15, 236, 496, 496, 756, 979), new ArtSlices(13, 243, 793, 793, 1340, 1572))),
            ["AnimePop"] = (
                new ArtFrameSlices(new ArtSlices(11, 294, 836, 836, 1380, 1661), new ArtSlices(16, 269, 470, 470, 672, 925)),
                new ArtFrameSlices(new ArtSlices(11, 329, 496, 496, 664, 982), new ArtSlices(18, 304, 793, 793, 1277, 1567))),
            ["ArtNouveau"] = (
                new ArtFrameSlices(new ArtSlices(8, 300, 668, 1005, 1373, 1665), new ArtSlices(8, 291, 470, 470, 640, 927)),
                new ArtFrameSlices(new ArtSlices(11, 348, 496, 496, 644, 982), new ArtSlices(6, 340, 793, 793, 1240, 1572))),
            ["BotanicalCottage"] = (
                new ArtFrameSlices(new ArtSlices(8, 324, 836, 836, 1348, 1665), new ArtSlices(16, 265, 470, 470, 671, 923)),
                new ArtFrameSlices(new ArtSlices(34, 328, 496, 496, 664, 958), new ArtSlices(44, 315, 793, 793, 1271, 1548))),
            ["CelestialSakura"] = (
                new ArtFrameSlices(new ArtSlices(0, 513, 552, 1120, 1159, 1672), new ArtSlices(4, 294, 318, 526, 550, 934)),
                new ArtFrameSlices(new ArtSlices(16, 344, 369, 629, 654, 976), new ArtSlices(13, 415, 452, 1025, 1062, 1574))),
            ["CorsairsFortune"] = (
                new ArtFrameSlices(new ArtSlices(22, 287, 836, 836, 1385, 1652), new ArtSlices(17, 269, 470, 470, 667, 915)),
                new ArtFrameSlices(new ArtSlices(13, 284, 496, 496, 711, 980), new ArtSlices(11, 286, 793, 793, 1302, 1574))),
            ["CrystariumCrystal"] = (
                new ArtFrameSlices(new ArtSlices(32, 232, 836, 836, 1441, 1642), new ArtSlices(35, 232, 470, 470, 706, 904)),
                new ArtFrameSlices(new ArtSlices(33, 269, 496, 496, 726, 960), new ArtSlices(54, 290, 793, 793, 1304, 1533))),
            ["CuteKawaii"] = (
                new ArtFrameSlices(new ArtSlices(0, 285, 641, 1032, 1387, 1672), new ArtSlices(0, 290, 470, 470, 624, 941)),
                new ArtFrameSlices(new ArtSlices(13, 336, 496, 496, 656, 979), new ArtSlices(14, 347, 793, 793, 1207, 1568))),
            ["CyberpunkNeon"] = (
                new ArtFrameSlices(new ArtSlices(12, 276, 756, 916, 1397, 1661), new ArtSlices(3, 260, 470, 470, 680, 931)),
                new ArtFrameSlices(new ArtSlices(11, 263, 496, 496, 731, 982), new ArtSlices(0, 257, 793, 793, 1281, 1554))),
            ["DarkAcademia"] = (
                new ArtFrameSlices(new ArtSlices(8, 261, 836, 836, 1413, 1665), new ArtSlices(17, 270, 470, 470, 665, 926)),
                new ArtFrameSlices(new ArtSlices(40, 302, 496, 496, 692, 953), new ArtSlices(47, 320, 793, 793, 1257, 1555))),
            ["DarkFantasy"] = (
                new ArtFrameSlices(new ArtSlices(24, 252, 836, 836, 1422, 1648), new ArtSlices(22, 257, 470, 470, 664, 893)),
                new ArtFrameSlices(new ArtSlices(12, 227, 496, 496, 764, 980), new ArtSlices(14, 246, 793, 793, 1330, 1564))),
            ["DesertOasis"] = (
                new ArtFrameSlices(new ArtSlices(22, 200, 836, 836, 1473, 1652), new ArtSlices(24, 255, 470, 470, 682, 914)),
                new ArtFrameSlices(new ArtSlices(26, 236, 496, 496, 759, 966), new ArtSlices(31, 245, 793, 793, 1341, 1554))),
            ["EmbroideredTapestry"] = (
                new ArtFrameSlices(new ArtSlices(18, 223, 836, 836, 1451, 1654), new ArtSlices(46, 265, 470, 470, 685, 910)),
                new ArtFrameSlices(new ArtSlices(7, 271, 496, 496, 719, 985), new ArtSlices(10, 331, 793, 793, 1275, 1556))),
            ["EnchantedToybox"] = (
                new ArtFrameSlices(new ArtSlices(11, 297, 836, 836, 1376, 1662), new ArtSlices(15, 333, 470, 470, 613, 926)),
                new ArtFrameSlices(new ArtSlices(25, 236, 496, 496, 756, 968), new ArtSlices(16, 276, 793, 793, 1309, 1571))),
            ["FrontierSilver"] = (
                new ArtFrameSlices(new ArtSlices(7, 235, 836, 836, 1438, 1666), new ArtSlices(10, 208, 470, 470, 729, 923)),
                new ArtFrameSlices(new ArtSlices(10, 272, 496, 496, 721, 982), new ArtSlices(6, 298, 793, 793, 1274, 1569))),
            ["HighFantasyRoyal"] = (
                new ArtFrameSlices(new ArtSlices(13, 247, 719, 954, 1426, 1660), new ArtSlices(0, 272, 470, 470, 673, 921)),
                new ArtFrameSlices(new ArtSlices(16, 314, 496, 496, 678, 977), new ArtSlices(22, 306, 793, 793, 1241, 1556))),
            ["IndustrialSalvage"] = (
                new ArtFrameSlices(new ArtSlices(19, 302, 836, 836, 1374, 1654), new ArtSlices(17, 241, 470, 470, 663, 902)),
                new ArtFrameSlices(new ArtSlices(33, 312, 496, 496, 681, 960), new ArtSlices(29, 259, 793, 793, 1296, 1538))),
            ["IshgardianGothic"] = (
                new ArtFrameSlices(new ArtSlices(13, 255, 836, 836, 1418, 1659), new ArtSlices(9, 246, 470, 470, 692, 930)),
                new ArtFrameSlices(new ArtSlices(38, 270, 496, 496, 724, 954), new ArtSlices(32, 265, 793, 793, 1315, 1554))),
            ["LiquidChrome"] = (
                new ArtFrameSlices(new ArtSlices(24, 282, 836, 836, 1388, 1648), new ArtSlices(16, 259, 470, 470, 685, 923)),
                new ArtFrameSlices(new ArtSlices(13, 305, 496, 496, 687, 979), new ArtSlices(0, 364, 793, 793, 1201, 1575))),
            ["MemphisPlayground"] = (
                new ArtFrameSlices(new ArtSlices(16, 249, 836, 836, 1423, 1657), new ArtSlices(16, 231, 470, 470, 706, 925)),
                new ArtFrameSlices(new ArtSlices(25, 245, 496, 496, 747, 967), new ArtSlices(14, 256, 793, 793, 1327, 1566))),
            ["MinimalistModern"] = (
                new ArtFrameSlices(new ArtSlices(31, 145, 836, 836, 1527, 1641), new ArtSlices(27, 143, 470, 470, 798, 911)),
                new ArtFrameSlices(new ArtSlices(33, 173, 496, 496, 820, 959), new ArtSlices(36, 175, 793, 793, 1411, 1550))),
            ["MosaicCourtyard"] = (
                new ArtFrameSlices(new ArtSlices(15, 215, 836, 836, 1458, 1658), new ArtSlices(35, 240, 470, 470, 703, 904)),
                new ArtFrameSlices(new ArtSlices(13, 230, 496, 496, 762, 980), new ArtSlices(18, 234, 793, 793, 1350, 1566))),
            ["OceanicSiren"] = (
                new ArtFrameSlices(new ArtSlices(22, 366, 836, 836, 1305, 1652), new ArtSlices(17, 307, 470, 470, 632, 913)),
                new ArtFrameSlices(new ArtSlices(28, 339, 496, 496, 654, 964), new ArtSlices(52, 369, 793, 793, 1200, 1513))),
            ["PaperTheater"] = (
                new ArtFrameSlices(new ArtSlices(28, 244, 836, 836, 1429, 1644), new ArtSlices(27, 240, 470, 470, 687, 901)),
                new ArtFrameSlices(new ArtSlices(24, 274, 496, 496, 719, 969), new ArtSlices(34, 286, 793, 793, 1268, 1534))),
            ["PorcelainGarden"] = (
                new ArtFrameSlices(new ArtSlices(27, 232, 836, 836, 1439, 1645), new ArtSlices(31, 233, 470, 470, 695, 906)),
                new ArtFrameSlices(new ArtSlices(22, 231, 496, 496, 762, 971), new ArtSlices(33, 249, 793, 793, 1337, 1553))),
            ["PrehistoricAmber"] = (
                new ArtFrameSlices(new ArtSlices(8, 283, 836, 836, 1390, 1664), new ArtSlices(12, 299, 470, 470, 673, 929)),
                new ArtFrameSlices(new ArtSlices(24, 302, 496, 496, 690, 968), new ArtSlices(16, 293, 793, 793, 1287, 1563))),
            ["PsychedelicBloom"] = (
                new ArtFrameSlices(new ArtSlices(14, 334, 836, 836, 1341, 1658), new ArtSlices(21, 310, 470, 470, 628, 919)),
                new ArtFrameSlices(new ArtSlices(31, 331, 496, 496, 661, 961), new ArtSlices(31, 362, 793, 793, 1223, 1554))),
            ["RacingCarbon"] = (
                new ArtFrameSlices(new ArtSlices(15, 299, 836, 836, 1373, 1657), new ArtSlices(12, 239, 470, 470, 697, 924)),
                new ArtFrameSlices(new ArtSlices(29, 300, 496, 496, 693, 963), new ArtSlices(41, 264, 793, 793, 1269, 1511))),
            ["RetroRPG"] = (
                new ArtFrameSlices(new ArtSlices(16, 204, 836, 836, 1468, 1657), new ArtSlices(15, 196, 470, 470, 745, 926)),
                new ArtFrameSlices(new ArtSlices(31, 224, 496, 496, 769, 962), new ArtSlices(38, 234, 793, 793, 1350, 1550))),
            ["RetroSpaceAge"] = (
                new ArtFrameSlices(new ArtSlices(8, 278, 836, 836, 1395, 1665), new ArtSlices(14, 271, 470, 470, 666, 926)),
                new ArtFrameSlices(new ArtSlices(20, 338, 496, 496, 655, 972), new ArtSlices(30, 331, 793, 793, 1224, 1523))),
            ["SteampunkMachinist"] = (
                new ArtFrameSlices(new ArtSlices(5, 246, 685, 988, 1426, 1667), new ArtSlices(0, 265, 470, 470, 657, 918)),
                new ArtFrameSlices(new ArtSlices(14, 304, 496, 496, 686, 978), new ArtSlices(15, 341, 793, 793, 1235, 1551))),
            ["SugarcraftPatisserie"] = (
                new ArtFrameSlices(new ArtSlices(1, 250, 836, 836, 1423, 1672), new ArtSlices(0, 227, 470, 470, 716, 941)),
                new ArtFrameSlices(new ArtSlices(14, 291, 496, 496, 702, 978), new ArtSlices(13, 332, 793, 793, 1248, 1568))),
            ["TarotArcana"] = (
                new ArtFrameSlices(new ArtSlices(18, 258, 836, 836, 1415, 1655), new ArtSlices(17, 288, 470, 470, 647, 910)),
                new ArtFrameSlices(new ArtSlices(16, 283, 496, 496, 709, 976), new ArtSlices(15, 319, 793, 793, 1265, 1559))),
            ["UkiyoeFantasy"] = (
                new ArtFrameSlices(new ArtSlices(15, 314, 836, 836, 1359, 1658), new ArtSlices(38, 253, 470, 470, 677, 904)),
                new ArtFrameSlices(new ArtSlices(47, 300, 496, 496, 692, 945), new ArtSlices(47, 264, 793, 793, 1274, 1537))),
            ["VelvetMasquerade"] = (
                new ArtFrameSlices(new ArtSlices(13, 248, 836, 836, 1425, 1660), new ArtSlices(19, 245, 470, 470, 690, 909)),
                new ArtFrameSlices(new ArtSlices(8, 284, 496, 496, 708, 985), new ArtSlices(16, 366, 793, 793, 1205, 1566))),
            ["VoidCosmicHorror"] = (
                new ArtFrameSlices(new ArtSlices(14, 320, 836, 836, 1352, 1659), new ArtSlices(15, 276, 470, 470, 664, 924)),
                new ArtFrameSlices(new ArtSlices(31, 321, 496, 496, 671, 962), new ArtSlices(37, 310, 793, 793, 1276, 1548))),
            ["VolcanicForge"] = (
                new ArtFrameSlices(new ArtSlices(24, 249, 836, 836, 1424, 1649), new ArtSlices(24, 249, 470, 470, 691, 916)),
                new ArtFrameSlices(new ArtSlices(8, 251, 496, 496, 743, 985), new ArtSlices(10, 295, 793, 793, 1291, 1575))),
            ["WatercolorFantasy"] = (
                new ArtFrameSlices(new ArtSlices(9, 294, 729, 944, 1379, 1664), new ArtSlices(12, 263, 470, 470, 678, 929)),
                new ArtFrameSlices(new ArtSlices(13, 291, 496, 496, 701, 979), new ArtSlices(25, 312, 793, 793, 1274, 1561))),
        };
}
