using System;
using System.Collections.Generic;
using System.Text.RegularExpressions;

namespace AetherFrame.Domain.Components;

/// <summary>
/// One runtime PNG that the plugin doesn't carry inside its assembly but downloads the first time a
/// player uses it (art on demand, the owner's choice of October 1, 2026): where it is, a commit of
/// this repository and its path below <c>AetherFrame/Assets</c>, and exactly what it is, its length
/// and SHA-256. The bytes are checked against both before anything decodes them, and hosted bytes
/// never change: new art gets a new artwork id and a new path.
/// </summary>
/// <param name="Path">The path below <c>AetherFrame/Assets</c>, with '/' separators
/// (<see cref="BuiltInArtAsset.AssetPath"/>).</param>
/// <param name="Length">The file's exact length, in bytes.</param>
/// <param name="Sha256">The file's SHA-256, 64 lowercase hex digits.</param>
/// <param name="Commit">The commit of this repository the file is downloaded from, 40 lowercase hex digits.</param>
public sealed record ArtFile(string Path, long Length, string Sha256, string Commit);

/// <summary>
/// The hosted artwork, generated by <c>tools/art/write_art_files.py</c> (ArtFiles.g.cs, with
/// <c>AetherFrame/Assets/ArtFiles.txt</c> as its plain-text twin for CI). Pure data: where and how
/// a file is downloaded is the networking flavour's (Services/Network/Transport/ArtHosting).
/// </summary>
public static partial class ArtFiles
{
    /// <summary>The longest file the table may name, in bytes: the largest piece is about 2.6 MB.</summary>
    public const long MaxLength = 8L * 1024 * 1024;

    private static readonly Regex CommitPattern = new("^[0-9a-f]{40}\\z", RegexOptions.CultureInvariant);
    private static readonly Regex Sha256Pattern = new("^[0-9a-f]{64}\\z", RegexOptions.CultureInvariant);
    private static readonly Regex PathPattern = new("^Components/[A-Za-z0-9_-]+/[A-Za-z0-9_-]+\\.png\\z", RegexOptions.CultureInvariant);

    /// <summary>Every hosted file, in path order.</summary>
    public static IReadOnlyList<ArtFile> All => Table;

    /// <summary>The hosted file at exactly <paramref name="path"/>, or null (paths are case-sensitive).</summary>
    public static ArtFile? Find(string? path) => path is not null && Index.ByPath.TryGetValue(path, out var file) ? file : null;

    /// <summary>True when every part of <paramref name="file"/> has the form a hosted file's must:
    /// a 40-hex commit, a 64-hex SHA-256, a length within <see cref="MaxLength"/>, and a path of
    /// letters, digits, '_' and '-' only, so nothing about it can change the address it is fetched from.</summary>
    public static bool IsWellFormed(ArtFile file) =>
        file is not null
        && CommitPattern.IsMatch(file.Commit)
        && Sha256Pattern.IsMatch(file.Sha256)
        && file.Length is > 0 and <= MaxLength
        && PathPattern.IsMatch(file.Path);

    /// <summary>
    /// The lookup, in a class of its own: field initializers across a partial class's files run in
    /// no defined order, and this one reads <see cref="Table"/>, from the generated file.
    /// </summary>
    private static class Index
    {
        internal static readonly Dictionary<string, ArtFile> ByPath = Build();

        private static Dictionary<string, ArtFile> Build()
        {
            var index = new Dictionary<string, ArtFile>(StringComparer.Ordinal);
            foreach (var file in Table)
            {
                index.Add(file.Path, file); // throws on a duplicate path: caught by any test run
            }

            return index;
        }
    }
}
