// <auto-generated>
// Written by tools/art/measure_frames.py from the frames' pixels: where each art set's Plate Frame
// and Portrait Frame is cut so it fits any box (ArtFrameSlices: columns, rows and the drawing's
// bounds, in runtime pixels). Edit the script and run it again rather than editing this file.
// </auto-generated>

using System;
using System.Collections.Generic;

namespace AetherFrame.Domain.Components;

internal static class ArtFrameData
{
    /// <summary>Each art set's Plate Frame and Portrait Frame cuts, by the set's folder (Celestial Sakura's included).</summary>
    internal static readonly IReadOnlyDictionary<string, (ArtFrameSlices PlateFrame, ArtFrameSlices PortraitFrame)> ByFolder =
        new Dictionary<string, (ArtFrameSlices PlateFrame, ArtFrameSlices PortraitFrame)>(StringComparer.Ordinal)
        {
            ["AlchemistsWorkshop"] = (
                new ArtFrameSlices(new ArtSlices(41, 291, 836, 836, 1382, 1632), new ArtSlices(44, 307, 470, 470, 627, 887), new ArtBounds(20, 14, 1654, 921)),
                new ArtFrameSlices(new ArtSlices(60, 265, 496, 496, 727, 932), new ArtSlices(75, 323, 793, 793, 1257, 1506), new ArtBounds(9, 9, 984, 1576))),
            ["AllaganTech"] = (
                new ArtFrameSlices(new ArtSlices(33, 239, 836, 836, 1433, 1640), new ArtSlices(34, 217, 470, 470, 707, 890), new ArtBounds(16, 16, 1657, 910)),
                new ArtFrameSlices(new ArtSlices(49, 270, 496, 496, 721, 943), new ArtSlices(64, 265, 793, 793, 1314, 1520), new ArtBounds(32, 44, 960, 1539))),
            ["AncientAmaurot"] = (
                new ArtFrameSlices(new ArtSlices(42, 230, 836, 836, 1442, 1632), new ArtSlices(40, 217, 470, 470, 724, 900), new ArtBounds(20, 15, 1653, 925)),
                new ArtFrameSlices(new ArtSlices(55, 236, 496, 496, 756, 937), new ArtSlices(57, 243, 793, 793, 1340, 1526), new ArtBounds(15, 13, 979, 1572))),
            ["AnimePop"] = (
                new ArtFrameSlices(new ArtSlices(33, 294, 836, 836, 1380, 1639), new ArtSlices(47, 269, 470, 470, 672, 894), new ArtBounds(11, 16, 1661, 925)),
                new ArtFrameSlices(new ArtSlices(36, 329, 496, 496, 664, 957), new ArtSlices(53, 304, 793, 793, 1277, 1532), new ArtBounds(11, 18, 982, 1567))),
            ["ArtNouveau"] = (
                new ArtFrameSlices(new ArtSlices(24, 300, 668, 1005, 1373, 1649), new ArtSlices(21, 291, 470, 470, 640, 920), new ArtBounds(8, 8, 1665, 927)),
                new ArtFrameSlices(new ArtSlices(32, 348, 496, 496, 644, 961), new ArtSlices(18, 340, 793, 793, 1240, 1555), new ArtBounds(11, 6, 982, 1572))),
            ["BotanicalCottage"] = (
                new ArtFrameSlices(new ArtSlices(34, 324, 836, 836, 1348, 1638), new ArtSlices(48, 265, 470, 470, 671, 895), new ArtBounds(8, 16, 1665, 923)),
                new ArtFrameSlices(new ArtSlices(55, 328, 496, 496, 664, 937), new ArtSlices(81, 315, 793, 793, 1271, 1505), new ArtBounds(34, 44, 958, 1548))),
            ["CelestialSakura"] = (
                new ArtFrameSlices(new ArtSlices(32, 513, 552, 1120, 1159, 1640), new ArtSlices(50, 294, 318, 526, 550, 895), new ArtBounds(0, 4, 1672, 934)),
                new ArtFrameSlices(new ArtSlices(79, 344, 369, 629, 654, 914), new ArtSlices(79, 415, 452, 1025, 1062, 1507), new ArtBounds(16, 13, 976, 1574))),
            ["CorsairsFortune"] = (
                new ArtFrameSlices(new ArtSlices(31, 287, 836, 836, 1385, 1642), new ArtSlices(31, 269, 470, 470, 667, 902), new ArtBounds(22, 17, 1652, 915)),
                new ArtFrameSlices(new ArtSlices(63, 284, 496, 496, 711, 930), new ArtSlices(67, 286, 793, 793, 1302, 1517), new ArtBounds(13, 11, 980, 1574))),
            ["CrystariumCrystal"] = (
                new ArtFrameSlices(new ArtSlices(60, 232, 836, 836, 1441, 1614), new ArtSlices(61, 232, 470, 470, 706, 878), new ArtBounds(32, 35, 1642, 904)),
                new ArtFrameSlices(new ArtSlices(58, 269, 496, 496, 726, 935), new ArtSlices(81, 290, 793, 793, 1304, 1504), new ArtBounds(33, 54, 960, 1533))),
            ["CuteKawaii"] = (
                new ArtFrameSlices(new ArtSlices(31, 285, 641, 1032, 1387, 1642), new ArtSlices(31, 290, 470, 470, 624, 910), new ArtBounds(0, 0, 1672, 941)),
                new ArtFrameSlices(new ArtSlices(52, 336, 496, 496, 656, 940), new ArtSlices(65, 347, 793, 793, 1207, 1533), new ArtBounds(13, 14, 979, 1568))),
            ["CyberpunkNeon"] = (
                new ArtFrameSlices(new ArtSlices(19, 276, 756, 916, 1397, 1655), new ArtSlices(24, 260, 470, 470, 680, 913), new ArtBounds(12, 3, 1661, 931)),
                new ArtFrameSlices(new ArtSlices(17, 263, 496, 496, 731, 976), new ArtSlices(20, 257, 793, 793, 1281, 1530), new ArtBounds(11, 0, 982, 1554))),
            ["DarkAcademia"] = (
                new ArtFrameSlices(new ArtSlices(32, 261, 836, 836, 1413, 1641), new ArtSlices(40, 270, 470, 470, 665, 888), new ArtBounds(8, 17, 1665, 926)),
                new ArtFrameSlices(new ArtSlices(63, 302, 496, 496, 692, 929), new ArtSlices(78, 320, 793, 793, 1257, 1507), new ArtBounds(40, 47, 953, 1555))),
            ["DarkFantasy"] = (
                new ArtFrameSlices(new ArtSlices(61, 252, 836, 836, 1422, 1611), new ArtSlices(59, 257, 470, 470, 664, 871), new ArtBounds(24, 22, 1648, 893)),
                new ArtFrameSlices(new ArtSlices(49, 227, 496, 496, 764, 943), new ArtSlices(49, 246, 793, 793, 1330, 1536), new ArtBounds(12, 14, 980, 1564))),
            ["DesertOasis"] = (
                new ArtFrameSlices(new ArtSlices(26, 200, 836, 836, 1473, 1648), new ArtSlices(31, 255, 470, 470, 682, 908), new ArtBounds(22, 24, 1652, 914)),
                new ArtFrameSlices(new ArtSlices(47, 236, 496, 496, 759, 945), new ArtSlices(51, 245, 793, 793, 1341, 1530), new ArtBounds(26, 31, 966, 1554))),
            ["EmbroideredTapestry"] = (
                new ArtFrameSlices(new ArtSlices(44, 223, 836, 836, 1451, 1629), new ArtSlices(57, 265, 470, 470, 685, 879), new ArtBounds(18, 46, 1654, 910)),
                new ArtFrameSlices(new ArtSlices(39, 271, 496, 496, 719, 953), new ArtSlices(25, 331, 793, 793, 1275, 1517), new ArtBounds(7, 10, 985, 1556))),
            ["EnchantedToybox"] = (
                new ArtFrameSlices(new ArtSlices(28, 297, 836, 836, 1376, 1644), new ArtSlices(50, 333, 470, 470, 613, 890), new ArtBounds(11, 15, 1662, 926)),
                new ArtFrameSlices(new ArtSlices(53, 236, 496, 496, 756, 940), new ArtSlices(67, 276, 793, 793, 1309, 1520), new ArtBounds(25, 16, 968, 1571))),
            ["FrontierSilver"] = (
                new ArtFrameSlices(new ArtSlices(21, 235, 836, 836, 1438, 1652), new ArtSlices(21, 208, 470, 470, 729, 911), new ArtBounds(7, 10, 1666, 923)),
                new ArtFrameSlices(new ArtSlices(32, 272, 496, 496, 721, 960), new ArtSlices(43, 298, 793, 793, 1274, 1534), new ArtBounds(10, 6, 982, 1569))),
            ["HighFantasyRoyal"] = (
                new ArtFrameSlices(new ArtSlices(32, 247, 719, 954, 1426, 1641), new ArtSlices(49, 272, 470, 470, 673, 894), new ArtBounds(13, 0, 1660, 921)),
                new ArtFrameSlices(new ArtSlices(36, 314, 496, 496, 678, 957), new ArtSlices(56, 306, 793, 793, 1241, 1532), new ArtBounds(16, 22, 977, 1556))),
            ["HoneybeeGarden"] = (
                new ArtFrameSlices(new ArtSlices(38, 338, 629, 1045, 1334, 1635), new ArtSlices(65, 357, 372, 566, 587, 883), new ArtBounds(4, 9, 1669, 927)),
                new ArtFrameSlices(new ArtSlices(40, 277, 362, 630, 714, 953), new ArtSlices(75, 376, 793, 793, 1188, 1508), new ArtBounds(21, 19, 971, 1547))),
            ["IndustrialSalvage"] = (
                new ArtFrameSlices(new ArtSlices(37, 302, 836, 836, 1374, 1636), new ArtSlices(31, 241, 470, 470, 663, 889), new ArtBounds(19, 17, 1654, 902)),
                new ArtFrameSlices(new ArtSlices(49, 312, 496, 496, 681, 943), new ArtSlices(41, 259, 793, 793, 1296, 1526), new ArtBounds(33, 29, 960, 1538))),
            ["IshgardianGothic"] = (
                new ArtFrameSlices(new ArtSlices(21, 255, 836, 836, 1418, 1651), new ArtSlices(38, 246, 470, 470, 692, 900), new ArtBounds(13, 9, 1659, 930)),
                new ArtFrameSlices(new ArtSlices(50, 270, 496, 496, 724, 943), new ArtSlices(63, 265, 793, 793, 1315, 1523), new ArtBounds(38, 32, 954, 1554))),
            ["LiquidChrome"] = (
                new ArtFrameSlices(new ArtSlices(44, 282, 836, 836, 1388, 1628), new ArtSlices(43, 259, 470, 470, 685, 897), new ArtBounds(24, 16, 1648, 923)),
                new ArtFrameSlices(new ArtSlices(36, 305, 496, 496, 687, 956), new ArtSlices(46, 364, 793, 793, 1201, 1528), new ArtBounds(13, 0, 979, 1575))),
            ["MemphisPlayground"] = (
                new ArtFrameSlices(new ArtSlices(22, 249, 836, 836, 1423, 1651), new ArtSlices(23, 231, 470, 470, 706, 918), new ArtBounds(16, 16, 1657, 925)),
                new ArtFrameSlices(new ArtSlices(36, 245, 496, 496, 747, 957), new ArtSlices(52, 256, 793, 793, 1327, 1529), new ArtBounds(25, 14, 967, 1566))),
            ["MinimalistModern"] = (
                new ArtFrameSlices(new ArtSlices(31, 145, 836, 836, 1527, 1641), new ArtSlices(27, 143, 470, 470, 798, 911), new ArtBounds(31, 27, 1641, 911)),
                new ArtFrameSlices(new ArtSlices(33, 173, 496, 496, 820, 959), new ArtSlices(36, 175, 793, 793, 1411, 1550), new ArtBounds(33, 36, 959, 1550))),
            ["MosaicCourtyard"] = (
                new ArtFrameSlices(new ArtSlices(31, 215, 836, 836, 1458, 1642), new ArtSlices(49, 240, 470, 470, 703, 891), new ArtBounds(15, 35, 1658, 904)),
                new ArtFrameSlices(new ArtSlices(13, 230, 496, 496, 762, 980), new ArtSlices(18, 234, 793, 793, 1350, 1566), new ArtBounds(13, 18, 980, 1566))),
            ["OceanicSiren"] = (
                new ArtFrameSlices(new ArtSlices(39, 366, 836, 836, 1305, 1634), new ArtSlices(48, 307, 470, 470, 632, 883), new ArtBounds(22, 17, 1652, 913)),
                new ArtFrameSlices(new ArtSlices(50, 339, 496, 496, 654, 942), new ArtSlices(109, 369, 793, 793, 1200, 1466), new ArtBounds(28, 52, 964, 1513))),
            ["PaperTheater"] = (
                new ArtFrameSlices(new ArtSlices(48, 244, 836, 836, 1429, 1625), new ArtSlices(49, 240, 470, 470, 687, 878), new ArtBounds(28, 27, 1644, 901)),
                new ArtFrameSlices(new ArtSlices(43, 274, 496, 496, 719, 950), new ArtSlices(58, 286, 793, 793, 1268, 1518), new ArtBounds(24, 34, 969, 1534))),
            ["PorcelainGarden"] = (
                new ArtFrameSlices(new ArtSlices(36, 232, 836, 836, 1439, 1636), new ArtSlices(43, 233, 470, 470, 695, 895), new ArtBounds(27, 31, 1645, 906)),
                new ArtFrameSlices(new ArtSlices(51, 231, 496, 496, 762, 943), new ArtSlices(65, 249, 793, 793, 1337, 1520), new ArtBounds(22, 33, 971, 1553))),
            ["PrehistoricAmber"] = (
                new ArtFrameSlices(new ArtSlices(23, 283, 836, 836, 1390, 1649), new ArtSlices(20, 299, 470, 470, 673, 921), new ArtBounds(8, 12, 1664, 929)),
                new ArtFrameSlices(new ArtSlices(60, 302, 496, 496, 690, 932), new ArtSlices(56, 293, 793, 793, 1287, 1522), new ArtBounds(24, 16, 968, 1563))),
            ["PsychedelicBloom"] = (
                new ArtFrameSlices(new ArtSlices(34, 334, 836, 836, 1341, 1638), new ArtSlices(39, 310, 470, 470, 628, 900), new ArtBounds(14, 21, 1658, 919)),
                new ArtFrameSlices(new ArtSlices(57, 331, 496, 496, 661, 936), new ArtSlices(59, 362, 793, 793, 1223, 1526), new ArtBounds(31, 31, 961, 1554))),
            ["RacingCarbon"] = (
                new ArtFrameSlices(new ArtSlices(18, 299, 836, 836, 1373, 1655), new ArtSlices(16, 239, 470, 470, 697, 919), new ArtBounds(15, 12, 1657, 924)),
                new ArtFrameSlices(new ArtSlices(75, 300, 496, 496, 693, 917), new ArtSlices(74, 264, 793, 793, 1269, 1471), new ArtBounds(29, 41, 963, 1511))),
            ["RetroRPG"] = (
                new ArtFrameSlices(new ArtSlices(34, 204, 836, 836, 1468, 1638), new ArtSlices(31, 196, 470, 470, 745, 907), new ArtBounds(16, 15, 1657, 926)),
                new ArtFrameSlices(new ArtSlices(53, 224, 496, 496, 769, 940), new ArtSlices(58, 234, 793, 793, 1350, 1527), new ArtBounds(31, 38, 962, 1550))),
            ["RetroSpaceAge"] = (
                new ArtFrameSlices(new ArtSlices(25, 278, 836, 836, 1395, 1648), new ArtSlices(31, 271, 470, 470, 666, 909), new ArtBounds(8, 14, 1665, 926)),
                new ArtFrameSlices(new ArtSlices(39, 338, 496, 496, 655, 953), new ArtSlices(52, 331, 793, 793, 1224, 1505), new ArtBounds(20, 30, 972, 1523))),
            ["SteampunkMachinist"] = (
                new ArtFrameSlices(new ArtSlices(24, 246, 685, 988, 1426, 1649), new ArtSlices(27, 265, 470, 470, 657, 901), new ArtBounds(5, 0, 1667, 918)),
                new ArtFrameSlices(new ArtSlices(39, 304, 496, 496, 686, 953), new ArtSlices(53, 341, 793, 793, 1235, 1524), new ArtBounds(14, 15, 978, 1551))),
            ["SugarcraftPatisserie"] = (
                new ArtFrameSlices(new ArtSlices(26, 250, 836, 836, 1423, 1647), new ArtSlices(21, 227, 470, 470, 716, 920), new ArtBounds(1, 0, 1672, 941)),
                new ArtFrameSlices(new ArtSlices(69, 291, 496, 496, 702, 924), new ArtSlices(66, 332, 793, 793, 1248, 1518), new ArtBounds(14, 13, 978, 1568))),
            ["TarotArcana"] = (
                new ArtFrameSlices(new ArtSlices(48, 258, 836, 836, 1415, 1625), new ArtSlices(64, 288, 470, 470, 647, 874), new ArtBounds(18, 17, 1655, 910)),
                new ArtFrameSlices(new ArtSlices(46, 283, 496, 496, 709, 946), new ArtSlices(72, 319, 793, 793, 1265, 1517), new ArtBounds(16, 15, 976, 1559))),
            ["UkiyoeFantasy"] = (
                new ArtFrameSlices(new ArtSlices(41, 314, 836, 836, 1359, 1632), new ArtSlices(51, 253, 470, 470, 677, 889), new ArtBounds(15, 38, 1658, 904)),
                new ArtFrameSlices(new ArtSlices(65, 300, 496, 496, 692, 928), new ArtSlices(72, 264, 793, 793, 1274, 1514), new ArtBounds(47, 47, 945, 1537))),
            ["VelvetMasquerade"] = (
                new ArtFrameSlices(new ArtSlices(43, 248, 836, 836, 1425, 1629), new ArtSlices(46, 245, 470, 470, 690, 892), new ArtBounds(13, 19, 1660, 909)),
                new ArtFrameSlices(new ArtSlices(52, 284, 496, 496, 708, 941), new ArtSlices(73, 366, 793, 793, 1205, 1508), new ArtBounds(8, 16, 985, 1566))),
            ["VoidCosmicHorror"] = (
                new ArtFrameSlices(new ArtSlices(45, 320, 836, 836, 1352, 1627), new ArtSlices(43, 276, 470, 470, 664, 894), new ArtBounds(14, 15, 1659, 924)),
                new ArtFrameSlices(new ArtSlices(62, 321, 496, 496, 671, 931), new ArtSlices(83, 310, 793, 793, 1276, 1502), new ArtBounds(31, 37, 962, 1548))),
            ["VolcanicForge"] = (
                new ArtFrameSlices(new ArtSlices(52, 249, 836, 836, 1424, 1620), new ArtSlices(52, 249, 470, 470, 691, 888), new ArtBounds(24, 24, 1649, 916)),
                new ArtFrameSlices(new ArtSlices(46, 251, 496, 496, 743, 947), new ArtSlices(66, 295, 793, 793, 1291, 1520), new ArtBounds(8, 10, 985, 1575))),
            ["WatercolorFantasy"] = (
                new ArtFrameSlices(new ArtSlices(40, 294, 729, 944, 1379, 1633), new ArtSlices(46, 263, 470, 470, 678, 892), new ArtBounds(9, 12, 1664, 929)),
                new ArtFrameSlices(new ArtSlices(39, 291, 496, 496, 701, 953), new ArtSlices(57, 312, 793, 793, 1274, 1527), new ArtBounds(13, 25, 979, 1561))),
        };
}
